[package]
name = "openhrt"
version = "0.1.0"
edition = "2024"

[dependencies]
macroquad = "0.4"
parking_lot = "0.12"
kira = { version = "0.10", default-features = false, features = ["cpal", "mp3", "flac"] }
